### ISSUE TITLE
ezMesh and easyMesh

### ISSUE THREAD

**Issue by BlackEdder** [sfranzyshen/ezMesh#1]
I am really interested in using a mesh network on my esps/arduinos and have been following easyMesh with interest. It seems though that this has been abandoned. Before I start my own project I was wondering if you were planning to do the same thing in this repository? If so I'd rather use yours/help out were I can, than start my own.

**Comment by sfranzyshen** [comment]
I am in the process of rewriting and expanding on the easyMesh. Because I am basically completely rewriting it ... and like you said the developer seams to have abandoned it ... I'm starting this project.

**Comment by BlackEdder** [comment]
Great to hear. I'll be keeping an eye on this :+1:

**Comment by BlackEdder** [comment]
@sfranzyshen Just wanted to invite you over to https://gitlab.com/BlackEdder/painlessMesh/. I decided to fork easyMesh so that I could at least maintain it, include fixes. The fork also contains your changes to the easyMesh. If you are interested in joining/working further on it, I'd be delighted to make you a member of the project.
